name: "Post-Anonymization Secrets Populator"
description: "Inserts your safe test config data into a database from a YAML file."
inputs:
  db_host:
    description: "Database host"
    required: true
  db_port:
    description: "Database port"
    required: true
  db_name:
    description: "Database name"
    required: true
  db_user:
    description: "Database user"
    required: true
  db_password:
    description: "Database password"
    required: true
  config_file:
    description: "YAML file with insert data"
    required: true
  commit_strategy:
    description: "How to commit changes: per_table or all_or_nothing"
    required: false
    default: "all_or_nothing"
  use_ssh_tunnel:
    description: "Use SSH tunnel to connect to the database"
    required: false
    default: "false"
  ssh_jump_host:
    description: "SSH jump host for tunneling"
    required: false
  ssh_jump_port:
    description: "SSH jump host port for tunneling"
    required: false
  ssh_jump_user:
    description: "SSH jump host user for tunneling"
    required: false
  ssh_jump_key:
    description: "SSH jump host private key for tunneling"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"